CREATE TABLE IF NOT EXISTS product
(
    id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    product_name VARCHAR NOT NULL,
    product_price INT NOT NULL DEFAULT 0,
    product_remains INT,
    is_deleted BOOLEAN NOT NULL DEFAULT false,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);